### PR TITLE
updates for more recent libraries

### PR DESCRIPTION
**Pull request by bmcfee**
This PR updates the benchmark suite for the following versions:

- soundfile 0.12.1 (with mp3 support)
- librosa 0.10
- scipy 1.9
- tensorflow 2.11
- tensorflow_io 0.30
- torch 1.13
- torchaudio 0.13

I wasn't able to get the docker instructions to work - apt is failing with some of the python dependencies.  The virtual environment sort of works, but requires special care when installing torch without GPU support.  I haven't bothered to update the instructions here, but they probably could use a general overhaul.

I have a run going on my dev machine currently, but the results aren't finished.  I expect these will be re-run by @faroit anyway, but let me know if anything needs to be done from the PR side.

### CODE REVIEW

**Comment by bmcfee** [comment]
Just bumping this one, since it's been quite a while. :grin:

**Comment by faroit** [comment]
@bmcfee sorry again. i forgot about this one

**Comment by faroit** [comment]
@bmcfee merged this for now and create new plots later

**Comment by bmcfee** [comment]
Awesome, thanks!

**Pull request merged**
