### PR TITLE
tensorflow2, librosa8, better plots

### PR DESCRIPTION
**Pull request by faroit**
* [x] update tensorflow to version 0.2.1
* [x] update librosa to 0.7.1
* [x] add tensorflow.io loading functions
* [x] update librosa to 0.8.0
* [x] removing gstreamer as its too slow

### Bug fixes

* [x] write 16bit wav files instead of 32bit wav files
* [x] change averaging according to #7 
* [x] fix tfio error handling

### CODE REVIEW

**Comment by bmcfee** [comment]
Gentle nudge on this one, since the reported librosa benchmarks are now two majors out of date :grin:

**Comment by faroit** [comment]
> Gentle nudge on this one, since the reported librosa benchmarks are now two majors out of date 😁

sorry again especially, since I am aware that this should be addressed soon as I never wanted to make librosa look bad in this...
That being said, I have two main issues that I could need could get some help with, as I am still lacking time to finish this up...
Basically you mentioned two things [here](https://github.com/faroit/python_audio_loading_benchmark/issues/7#issuecomment-576871419):

1. __Use timit to launch individual file loadings to reduce warm-up bias:__ I will propose something, maybe you could review that.
2. __Change the plotting to swarm plots:__ I played with that but I wasn't that successful in getting something that brings a clear message to viewers. I could provide the pandas files so you may play with that

3. __tf.data pipelines aren't really playing nice with errors (such as when a file format is not supported)__ using 

```dataset = dataset.apply(tf.data.experimental.ignore_errors())``` results in no errors at all, thus making it even even harder to track down if the data was loaded successfully. So I guess I have to check the actual return value... any other idea?

**Comment by faroit** [comment]
@bmcfee regarding 3. I guess the easiest is to have fixed matrix of supported pairs of codecs and libs that will be tested instead of using try/except...

**Comment by bmcfee** [comment]
>     1. I will propose something, maybe you could review that.

Sure, happy to!



>     2\. I played with that but I wasn't that successful in getting something that brings a clear message to viewers. I could provide the pandas files so you may play with that

That's fine -- it was just a suggestion.  I generally have a preference toward raw data over aggregates, but if it's too unwieldy here, there's no problem leaving it as is.



>  results in no errors at all, thus making it even even harder to track down if the data was loaded successfully. So I guess I have to check the actual return value... any other idea?

Hrm, indeed.  I guess you could do a length check (expected # of samples) if you don't want to do a full inspection of the data.



> I guess the easiest is to have fixed matrix of supported pairs of codecs and libs that will be tested instead of using try/except...

That's probably a safer option, but a lot more work I'm guessing.

**Comment by faroit** [comment]
@bmcfee a problem with 1. is that tf.data pipelines need to be compiled for each file. That would make the comparison between frameworks (np vs torch vs tf) useless as tf would probably be last. Still it would be meaningful to give relative results: aka. which loading method is the fasted for each tensor lib. Would you say this is worth it then?

**Comment by bmcfee** [comment]
>  That would make the comparison between frameworks (np vs torch vs tf) useless as tf would probably be last. Still it would be meaningful to give relative results: aka. which loading method is the fasted for each tensor lib. Would you say this is worth it then?

Yeah, that's tricky.  Maybe worth reporting two versions in that case, one of which factors out the compilation time?

**Comment by faroit** [comment]
@bmcfee i think its better to merge this now than waiting another year... sorry for this.
I didn't had time to polish the plots but all libs are up to date and i am using timit to get a better average

**Comment by bmcfee** [comment]
Thanks @faroit !  I'm just happy to see the version updates. :grin:

**Pull request merged**
